// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/qmdx00/crobjob/internal/task/biz"
	"github.com/qmdx00/crobjob/internal/task/config"
	"github.com/qmdx00/crobjob/internal/task/log"
	"github.com/qmdx00/crobjob/internal/task/server"
	"github.com/qmdx00/crobjob/pkg/lifecycle"
)

// Injectors from wire.go:

func initApp() (*lifecycle.App, func(), error) {
	taskConfig := config.NewTaskConfig()
	logger := log.NewTaskLogger(taskConfig)
	taskBusiness := biz.NewTaskBusiness(logger)
	grpcServer, cleanup, err := server.NewGRPCServer(taskBusiness, taskConfig)
	if err != nil {
		return nil, nil, err
	}
	transportServer := server.NewServer(logger, grpcServer, taskConfig)
	app := newApp(transportServer)
	return app, func() {
		cleanup()
	}, nil
}
