// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/qmdx00/crobjob/internal/task/biz"
	"github.com/qmdx00/crobjob/internal/task/log"
	"github.com/qmdx00/crobjob/internal/task/server"
	"github.com/qmdx00/crobjob/pkg/lifecycle"
)

// Injectors from wire.go:

func initApp() (*lifecycle.App, func(), error) {
	logger := log.NewTaskLogger()
	taskBusiness := biz.NewTaskBusiness(logger)
	grpcServer := server.NewGRPC(taskBusiness)
	transportServer, err := server.NewServer(logger, grpcServer)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(transportServer)
	return app, func() {
	}, nil
}
